# Generated by Django 4.2.4 on 2023-08-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_login_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name_plural': 'Signup'},
        ),
    ]
