# Generated by Django 4.2.4 on 2023-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_avatar', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField()),
                ('products', models.ManyToManyField(to='inventory.product')),
            ],
        ),
    ]
