# Generated by Django 4.2.4 on 2023-08-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycart',
            options={'verbose_name_plural': 'My cart'},
        ),
    ]
